# Basic colors
foreground              #e0e2e8
background              #101418
selection_foreground    #243240
selection_background    #bac8da

# Cursor colors
cursor                  #9dcafc
cursor_text_color       #003355

# URL underline color when hovering with mouse
url_color               #d5bee5

# Kitty window border colors
active_border_color     #9dcafc
inactive_border_color   #42474e
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #003355
active_tab_background   #9dcafc
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
tab_bar_background      #101418

# Colors for marks
mark1_foreground #003355
mark1_background #9dcafc
mark2_foreground #243240
mark2_background #bac8da
mark3_foreground #3a2a48
mark3_background #d5bee5

# The 16 terminal colors
# black
color0 #101418
color8 #42474e

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #9dcafc
color10 #9dcafc

# yellow
color3  #d5bee5
color11 #d5bee5

# blue
color4  #bac8da
color12 #bac8da

# magenta
color5  #d0e4ff
color13 #d0e4ff

# cyan
color6  #f0dbff
color14 #f0dbff

# white
color7  #e0e2e8
color15 #e0e2e8
