# ML4W tarzı Kitty yapılandırması
# Kaynak: https://github.com/mylinuxforwork/dotfiles

# Font
font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto

# Pencere
remember_window_size        no
initial_window_width        950
initial_window_height       500
window_padding_width        10
hide_window_decorations     yes
confirm_os_window_close     0

# İmleç
cursor_blink_interval       0.5
cursor_stop_blinking_after  1

# Kaydırma ve zil
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no

# Seçim
selection_foreground        none
selection_background        none

# Şeffaflık
background_opacity          0.7
dynamic_background_opacity  yes

# Renkler (matugen tarafından üretilir)
include /tmp/kitty-matugen-colors.conf

# Kullanıcı özel geçersiz kılmaları için
include ~/.config/kitty/custom.conf
